version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: male_fashion
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: male_fashion
      MYSQL_USER: user
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql